name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create PR to develop
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base develop \
            --head "${{ github.ref_name }}" \
            --title "Merge ${{ github.ref_name }} into develop" \
            --body "Automatically created PR"